name: ucfbox
description: UCFBox

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.7

  cupertino_icons: ^0.1.2
  flutter_swiper : ^1.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/